### ISSUE TITLE
Adding SUSClk

### ISSUE THREAD

**Issue by speters** [PineberryPi/pineberry-docs.github.io#1]
Thx for your product!

See my comment in https://github.com/raspberrypi/linux/issues/5217#issuecomment-1864927101 about adding SUSClk signal to make some disks work.

![IMG_20231220_174152_resized](https://github.com/PineberryPi/pineberry-docs.github.io/assets/1384994/9734582d-ebf8-45c1-a87d-8772848b0ad0)

With a 32khz signal from the RTC of another board fed to SUSClk (pull-up resistor to 3.3V was needed for open drain output of the RTC's osc pin, I soldered a 0402 size R directly between SUSclk/Pin68 and 3.3V/Pin70 ) it now works like a charm.

Maybe you could add a simple 32khz oscillator to the next rev. of your board. Should not add too much in parts costs.

**Comment by mikegapinski** [comment]
It'll show up on the HatDrive Bottom once we ship all the inventory, the boards we are making for the next drop have SUSClk

<img width="1419" alt="image" src="https://github.com/PineberryPi/pineberry-docs.github.io/assets/930055/4d24a1cd-8912-472c-a59b-0759f34e72fd">

**Comment by speters** [comment]
I now built a similar circuit using a [JRO32 32kHz oscillator](http://web.archive.org/web/20240108155121/https://www.jauch.com/downloadfile/57ff8a106f744_9627f8da1f8128e615cf/jro32_180618.pdf). Circuit is built by scoring traces/pads into some GND fill of the original PCB:

![IMG_20240108_153750_corr](https://github.com/PineberryPi/pineberry-docs.github.io/assets/1384994/424335ea-a888-45ec-ba86-a73534fdf2e0)

PS:
I also wasn't happy with the brass NVME disk holder, as it is inpossible to replace the NVME disk when the PineBerry PCB is mounted to the Pi5. My solution was to cut it down with a fret saw and solder it in. Now the screw is accessible.
