### ISSUE TITLE
Please document HatDrive BMIL connector power type 

### ISSUE THREAD

**Issue by awto-au** [PineberryPi/pineberry-docs.github.io#11]

**Comment by mlewus** [comment]
Ditto. If someone from Pineberry posts the manufacturer and part number of the aux power PCB receptacle, I offer to find and post the part numbers of the mating plug, contacts, and pre-made cables (if available) from the usual parts distributors in the US and Europe.

**Comment by singlebeam** [comment]
Please! I've been endlessly searching for more info on this and it seems like there are many people out there wondering the same thing.

**Comment by mlewus** [comment]
Many larger capacity ssds require more than the 5 watt power limit supplied by the Raspberry Pi pcie connector. When an SSD fails to work the first thing you're going to want to try is to add additional power, but this is presently difficult to do.

**Comment by awto-au** [comment]
Hi. Here to answer my own question - I believe it is a ZH connector.
