### ISSUE TITLE
Link to support / indicate alpha quality

### ISSUE THREAD

**Issue by ffries** [PineberryPi/pineberry-docs.github.io#6]
Dear all,

I am a user of a bottom hat version 1.

I cannot  boot from a Western Digital SN570.
The disk is recognized when booting from micro-SD.
I know this could be a problem with wiring on the PCI cap with a capacitor.

Some remarks:
* The website indicates a link to Raspberry Linux for support and I think there should be a link to a support page. 
* I don't connect to Twitter/X. So please don't propose any support on X.  Github is a nice place for support.
* We need more information. For example I still don't understand how to obtain a serial console. I purchased a Rpi debugger and I don't know whether I can simple connect using RTC.
* The hardware should be marked ALPHA quality as it truly is.
* Although Poland is in the European-Union, I had to pay VAT taxes on import and this is quite unusual which adds to price + shipping +++
* I am prepared to do the wiring of the board revision 1 otherwize I would like to receive an updated version. Please explain publicly how to fix the card revision 1.
* You should consider stopping taking orders before the dust settles down (for a few days only). People are not willing to receive alpha quality board at least pay for alpha.

Besides, I like your products and I will probably need 3 more bottom caps and 2 top caps. But I need real products; not alpha untested products. The marker is huge if you think of datacenters, so please give more updated information. 

Kind regards,
FFries

**Comment by mikegapinski** [comment]
WD drives are problematic on the Pi 5 and CM4 - those issues come from the firmware on the drive (that we do not make) or the Pi 5 bootloader (if the drive is detected in the OS), we also do not make the bootloader firmware. That is why I linked to the eeprom repo, WD issues happen on all other NVMe boards too.

_We need more information. For example I still don't understand how to obtain a serial console. I purchased a Rpi debugger and I don't know whether I can simple connect using RTC._

This is not related to our boards, please use the official Pi 5 forum or GitHub in their organisation.

_I am prepared to do the wiring of the board revision 1 otherwize I would like to receive an updated version. Please explain publicly how to fix the card revision 1._

There is nothing to fix on this board, updates to the design would be mostly around optimization of the manufacturing process.
